### ISSUE TITLE
Future Warning pandas.core.datatools deprecated.

### ISSUE THREAD

**Issue by jjpopski** [matteobachetti/srt-single-dish-tools#63]
`matplotlib.use(DEFAULT_MPL_BACKEND)`

> /home/spoppi/anaconda3/envs/py3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
>   from pandas.core import datetools
> usage: SDTimage [-h] [--sample-config] [-c CONFIG] [--refilt] [--altaz]
>                 [--sub] [--interactive] [--calibrate CALIBRATE] [--nofilt]
>                 [-g] [-e EXCLUDE [EXCLUDE ...]] [--chans CHANS] [-o OUTFILE]
>                 [-u UNIT] [--destripe] [--npix-tol NPIX_TOL] [--debug]
>                 [--quick] [--scrunch-channels] [--splat SPLAT]
>                 [file]
> 

Load a series of scans from a config file and produce a map.`

**Comment by matteobachetti** [comment]
Thanks @jjpopski!

This is fixed in the `master` version of `statsmodels`, it will be updated soon: https://github.com/statsmodels/statsmodels/pull/3618
